package com.tylerh.extraores.World;

import com.tylerh.extraores.Init.ConfiguredFeatureList;
import com.tylerh.extraores.Init.PlacedFeatureList;
import com.tylerh.extraores.Util.ModInfo;
import net.minecraft.core.Holder;
import net.minecraft.core.registries.Registries;
import net.minecraft.data.worldgen.BootstrapContext;
import net.minecraft.resources.ResourceKey;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.level.levelgen.VerticalAnchor;
import net.minecraft.world.level.levelgen.feature.ConfiguredFeature;
import net.minecraft.world.level.levelgen.placement.*;

import java.util.List;

public class ExOrePlacedFeature
{
    public static void bootstrap(BootstrapContext<PlacedFeature> context)
    {
        int rate = 20;
        int height;
        var configuredFeatures = context.lookup(Registries.CONFIGURED_FEATURE);
            PlacedFeatureList.placedFeatureAdamantine = createKey("adamantineore");
            height = ModInfo.HEIGHT_RARE;
            register(context,PlacedFeatureList.placedFeatureAdamantine,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureAdamantine),rate,height);
            PlacedFeatureList.placedFeatureAgate = createKey("agateore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureAgate,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureAgate),rate,height);
            PlacedFeatureList.placedFeatureAldourite = createKey("aldouriteore");
            height = ModInfo.HEIGHT_NETHER;
            register(context,PlacedFeatureList.placedFeatureAldourite,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureAldourite),rate,height);
            PlacedFeatureList.placedFeatureAluminum = createKey("aluminumore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureAluminum,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureAluminum),rate,height);
            PlacedFeatureList.placedFeatureAmericium = createKey("americiumore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureAmericium,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureAmericium),rate,height);
            PlacedFeatureList.placedFeatureAmethyst = createKey("amethystore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureAmethyst,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureAmethyst),rate,height);
            PlacedFeatureList.placedFeatureAmetrine = createKey("ametrineore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureAmetrine,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureAmetrine),rate,height);
            PlacedFeatureList.placedFeatureAmordrine = createKey("amordrineore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureAmordrine,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureAmordrine),rate,height);
            PlacedFeatureList.placedFeatureAngmallen = createKey("angmallenore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureAngmallen,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureAngmallen),rate,height);
            PlacedFeatureList.placedFeatureAquamarine = createKey("aquamarineore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureAquamarine,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureAquamarine),rate,height);
            PlacedFeatureList.placedFeatureAstralSilver = createKey("astralsilverore");
            height = ModInfo.HEIGHT_RARE;
            register(context,PlacedFeatureList.placedFeatureAstralSilver,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureAstralSilver),rate,height);
            PlacedFeatureList.placedFeatureAtlarus = createKey("atlarusore");
            height = ModInfo.HEIGHT_RARE;
            register(context,PlacedFeatureList.placedFeatureAtlarus,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureAtlarus),rate,height);
            PlacedFeatureList.placedFeatureAzureSilver = createKey("azuresilverore");
            height = ModInfo.HEIGHT_RARE;
            register(context,PlacedFeatureList.placedFeatureAzureSilver,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureAzureSilver),rate,height);
            PlacedFeatureList.placedFeatureBismuth = createKey("bismuthore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureBismuth,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureBismuth),rate,height);
            PlacedFeatureList.placedFeatureBlackSteel = createKey("blacksteelore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureBlackSteel,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureBlackSteel),rate,height);
            PlacedFeatureList.placedFeatureCadmium = createKey("cadmiumore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureCadmium,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureCadmium),rate,height);
            PlacedFeatureList.placedFeatureCarmot = createKey("carmotore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureCarmot,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureCarmot),rate,height);
            PlacedFeatureList.placedFeatureCelenegil = createKey("celenegilore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureCelenegil,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureCelenegil),rate,height);
            PlacedFeatureList.placedFeatureCeruclase = createKey("ceruclaseore");
            height = ModInfo.HEIGHT_NETHER;
            register(context,PlacedFeatureList.placedFeatureCeruclase,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureCeruclase),rate,height);
            PlacedFeatureList.placedFeatureChromium = createKey("chromiumore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureChromium,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureChromium),rate,height);
            PlacedFeatureList.placedFeatureChrysocolla = createKey("chrysocollaore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureChrysocolla,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureChrysocolla),rate,height);
            PlacedFeatureList.placedFeatureCitrine = createKey("citrineore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureCitrine,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureCitrine),rate,height);
            PlacedFeatureList.placedFeatureCobalt = createKey("cobaltore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureCobalt,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureCobalt),rate,height);
            PlacedFeatureList.placedFeatureCopper = createKey("copperore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureCopper,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureCopper),rate,height);
            PlacedFeatureList.placedFeatureCrimsonSteel = createKey("crimsonsteelore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureCrimsonSteel,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureCrimsonSteel),rate,height);
            PlacedFeatureList.placedFeatureDeepIron = createKey("deepironore");
            height = ModInfo.HEIGHT_RARE;
            register(context,PlacedFeatureList.placedFeatureDeepIron,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureDeepIron),rate,height);
            PlacedFeatureList.placedFeatureDesichalkos = createKey("desichalkosore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureDesichalkos,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureDesichalkos),rate,height);
            PlacedFeatureList.placedFeatureEximite = createKey("eximiteore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureEximite,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureEximite),rate,height);
            PlacedFeatureList.placedFeatureGallium = createKey("galliumore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureGallium,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureGallium),rate,height);
            PlacedFeatureList.placedFeatureGarnet = createKey("garnetore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureGarnet,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureGarnet),rate,height);
            PlacedFeatureList.placedFeatureHaderoth = createKey("haderothore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureHaderoth,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureHaderoth),rate,height);
            PlacedFeatureList.placedFeatureHepatizon = createKey("hepatizonore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureHepatizon,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureHepatizon),rate,height);
            PlacedFeatureList.placedFeatureIgnatius = createKey("ignatiusore");
            height = ModInfo.HEIGHT_NETHER;
            register(context,PlacedFeatureList.placedFeatureIgnatius,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureIgnatius),rate,height);
            PlacedFeatureList.placedFeatureIndium = createKey("indiumore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureIndium,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureIndium),rate,height);
            PlacedFeatureList.placedFeatureInfuscolium = createKey("infuscoliumore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureInfuscolium,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureInfuscolium),rate,height);
            PlacedFeatureList.placedFeatureInolashite = createKey("inolashiteore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureInolashite,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureInolashite),rate,height);
            PlacedFeatureList.placedFeatureIolite = createKey("ioliteore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureIolite,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureIolite),rate,height);
            PlacedFeatureList.placedFeatureIridium = createKey("iridiumore");
            height = ModInfo.HEIGHT_RARE;
            register(context,PlacedFeatureList.placedFeatureIridium,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureIridium),rate,height);
            PlacedFeatureList.placedFeatureJade = createKey("jadeore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureJade,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureJade),rate,height);
            PlacedFeatureList.placedFeatureJasper = createKey("jasperore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureJasper,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureJasper),rate,height);
            PlacedFeatureList.placedFeatureKalendrite = createKey("kalendriteore");
            height = ModInfo.HEIGHT_NETHER;
            register(context,PlacedFeatureList.placedFeatureKalendrite,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureKalendrite),rate,height);
            PlacedFeatureList.placedFeatureKyanite = createKey("kyaniteore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureKyanite,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureKyanite),rate,height);
            PlacedFeatureList.placedFeatureLead = createKey("leadore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureLead,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureLead),rate,height);
            PlacedFeatureList.placedFeatureLemurite = createKey("lemuriteore");
            height = ModInfo.HEIGHT_NETHER;
            register(context,PlacedFeatureList.placedFeatureLemurite,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureLemurite),rate,height);
            PlacedFeatureList.placedFeatureMalachite = createKey("malachiteore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureMalachite,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureMalachite),rate,height);
            PlacedFeatureList.placedFeatureManganese = createKey("manganeseore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureManganese,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureManganese),rate,height);
            PlacedFeatureList.placedFeatureMeutoite = createKey("meutoiteore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureMeutoite,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureMeutoite),rate,height);
            PlacedFeatureList.placedFeatureMidasium = createKey("midasiumore");
            height = ModInfo.HEIGHT_NETHER;
            register(context,PlacedFeatureList.placedFeatureMidasium,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureMidasium),rate,height);
            PlacedFeatureList.placedFeatureMithril = createKey("mithrilore");
            height = ModInfo.HEIGHT_RARE;
            register(context,PlacedFeatureList.placedFeatureMithril,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureMithril),rate,height);
            PlacedFeatureList.placedFeatureMolybdenum = createKey("molybdenumore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureMolybdenum,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureMolybdenum),rate,height);
            PlacedFeatureList.placedFeatureNeodymium = createKey("neodymiumore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureNeodymium,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureNeodymium),rate,height);
            PlacedFeatureList.placedFeatureNeptunium = createKey("neptuniumore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureNeptunium,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureNeptunium),rate,height);
            PlacedFeatureList.placedFeatureNickel = createKey("nickelore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureNickel,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureNickel),rate,height);
            PlacedFeatureList.placedFeatureNiobium = createKey("niobiumore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureNiobium,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureNiobium),rate,height);
            PlacedFeatureList.placedFeatureOnyx = createKey("onyxore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureOnyx,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureOnyx),rate,height);
            PlacedFeatureList.placedFeatureOpal = createKey("opalore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureOpal,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureOpal),rate,height);
            PlacedFeatureList.placedFeatureOrichalcum = createKey("orichalcumore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureOrichalcum,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureOrichalcum),rate,height);
            PlacedFeatureList.placedFeatureOsmium = createKey("osmiumore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureOsmium,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureOsmium),rate,height);
            PlacedFeatureList.placedFeatureOureclase = createKey("oureclaseore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureOureclase,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureOureclase),rate,height);
            PlacedFeatureList.placedFeaturePalladium = createKey("palladiumore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeaturePalladium,configuredFeatures.getOrThrow(ConfiguredFeatureList.featurePalladium),rate,height);
            PlacedFeatureList.placedFeaturePeridot = createKey("peridotore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeaturePeridot,configuredFeatures.getOrThrow(ConfiguredFeatureList.featurePeridot),rate,height);
            PlacedFeatureList.placedFeaturePhoenixite = createKey("phoenixiteore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeaturePhoenixite,configuredFeatures.getOrThrow(ConfiguredFeatureList.featurePhoenixite),rate,height);
            PlacedFeatureList.placedFeaturePlatinum = createKey("platinumore");
            height = ModInfo.HEIGHT_RARE;
            register(context,PlacedFeatureList.placedFeaturePlatinum,configuredFeatures.getOrThrow(ConfiguredFeatureList.featurePlatinum),rate,height);
            PlacedFeatureList.placedFeaturePlutonium = createKey("plutoniumore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeaturePlutonium,configuredFeatures.getOrThrow(ConfiguredFeatureList.featurePlutonium),rate,height);
            PlacedFeatureList.placedFeaturePolonium = createKey("poloniumore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeaturePolonium,configuredFeatures.getOrThrow(ConfiguredFeatureList.featurePolonium),rate,height);
            PlacedFeatureList.placedFeaturePromethium = createKey("promethiumore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeaturePromethium,configuredFeatures.getOrThrow(ConfiguredFeatureList.featurePromethium),rate,height);
            PlacedFeatureList.placedFeatureQuartz = createKey("quartzore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureQuartz,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureQuartz),rate,height);
            PlacedFeatureList.placedFeatureRhenium = createKey("rheniumore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureRhenium,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureRhenium),rate,height);
            PlacedFeatureList.placedFeatureRhodium = createKey("rhodiumore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureRhodium,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureRhodium),rate,height);
            PlacedFeatureList.placedFeatureRubracium = createKey("rubraciumore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureRubracium,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureRubracium),rate,height);
            PlacedFeatureList.placedFeatureRuby = createKey("rubyore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureRuby,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureRuby),rate,height);
            PlacedFeatureList.placedFeatureRuthenium = createKey("rutheniumore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureRuthenium,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureRuthenium),rate,height);
            PlacedFeatureList.placedFeatureSanguinite = createKey("sanguiniteore");
            height = ModInfo.HEIGHT_NETHER;
            register(context,PlacedFeatureList.placedFeatureSanguinite,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureSanguinite),rate,height);
            PlacedFeatureList.placedFeatureSapphire = createKey("sapphireore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureSapphire,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureSapphire),rate,height);
            PlacedFeatureList.placedFeatureShadowIron = createKey("shadowironore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureShadowIron,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureShadowIron),rate,height);
            PlacedFeatureList.placedFeatureSilver = createKey("silverore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureSilver,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureSilver),rate,height);
            PlacedFeatureList.placedFeatureSpinel = createKey("spinelore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureSpinel,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureSpinel),rate,height);
            PlacedFeatureList.placedFeatureSugilite = createKey("sugiliteore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureSugilite,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureSugilite),rate,height);
            PlacedFeatureList.placedFeatureTantalum = createKey("tantalumore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureTantalum,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureTantalum),rate,height);
            PlacedFeatureList.placedFeatureTanzanite = createKey("tanzaniteore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureTanzanite,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureTanzanite),rate,height);
            PlacedFeatureList.placedFeatureTartarite = createKey("tartariteore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureTartarite,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureTartarite),rate,height);
            PlacedFeatureList.placedFeatureTechnetium = createKey("technetiumore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureTechnetium,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureTechnetium),rate,height);
            PlacedFeatureList.placedFeatureThallium = createKey("thalliumore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureThallium,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureThallium),rate,height);
            PlacedFeatureList.placedFeatureTin = createKey("tinore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureTin,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureTin),rate,height);
            PlacedFeatureList.placedFeatureTitanium = createKey("titaniumore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureTitanium,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureTitanium),rate,height);
            PlacedFeatureList.placedFeatureTopaz = createKey("topazore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureTopaz,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureTopaz),rate,height);
            PlacedFeatureList.placedFeatureTourmaline = createKey("tourmalineore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureTourmaline,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureTourmaline),rate,height);
            PlacedFeatureList.placedFeatureTritium = createKey("tritiumore");
            height = ModInfo.HEIGHT_RARE;
            register(context,PlacedFeatureList.placedFeatureTritium,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureTritium),rate,height);
            PlacedFeatureList.placedFeatureTungsten = createKey("tungstenore");
            height = ModInfo.HEIGHT_RARE;
            register(context,PlacedFeatureList.placedFeatureTungsten,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureTungsten),rate,height);
            PlacedFeatureList.placedFeatureTurquoise = createKey("turquoiseore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureTurquoise,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureTurquoise),rate,height);
            PlacedFeatureList.placedFeatureUnobtainium = createKey("unobtainiumore");
            height = ModInfo.HEIGHT_RARE;
            register(context,PlacedFeatureList.placedFeatureUnobtainium,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureUnobtainium),rate,height);
            PlacedFeatureList.placedFeatureUranium = createKey("uraniumore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureUranium,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureUranium),rate,height);
            PlacedFeatureList.placedFeatureVanadium = createKey("vanadiumore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureVanadium,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureVanadium),rate,height);
            PlacedFeatureList.placedFeatureVibranium = createKey("vibraniumore");
            height = ModInfo.HEIGHT_RARE;
            register(context,PlacedFeatureList.placedFeatureVibranium,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureVibranium),rate,height);
            PlacedFeatureList.placedFeatureVulcanite = createKey("vulcaniteore");
            height = ModInfo.HEIGHT_NETHER;
            register(context,PlacedFeatureList.placedFeatureVulcanite,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureVulcanite),rate,height);
            PlacedFeatureList.placedFeatureVyroxeres = createKey("vyroxeresore");
            height = ModInfo.HEIGHT_NETHER;
            register(context,PlacedFeatureList.placedFeatureVyroxeres,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureVyroxeres),rate,height);
            PlacedFeatureList.placedFeatureYellorite = createKey("yelloriteore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureYellorite,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureYellorite),rate,height);
            PlacedFeatureList.placedFeatureZinc = createKey("zincore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureZinc,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureZinc),rate,height);
            PlacedFeatureList.placedFeatureZirconium = createKey("zirconiumore");
            height = ModInfo.HEIGHT_NORMAL;
            register(context,PlacedFeatureList.placedFeatureZirconium,configuredFeatures.getOrThrow(ConfiguredFeatureList.featureZirconium),rate,height);
    }
    private static ResourceKey<PlacedFeature> createKey(String name)
    {
        return ResourceKey.create(Registries.PLACED_FEATURE,ResourceLocation.fromNamespaceAndPath(ModInfo.MOD_ID,name));
    }
    private static void register(BootstrapContext<PlacedFeature> context, ResourceKey<PlacedFeature> key, Holder<ConfiguredFeature<?,?>> configuration, int rate, int height)
    {
        context.register(key,new PlacedFeature(configuration,List.of(CountPlacement.of(rate), InSquarePlacement.spread(), HeightRangePlacement.uniform(VerticalAnchor.BOTTOM,VerticalAnchor.aboveBottom(height)), BiomeFilter.biome())));
    }
}
