package com.tylerh.extraores.Util;

import net.neoforged.neoforge.common.ModConfigSpec;

public class ExOresConfig
{
    public static ModConfigSpec.Builder BUILDER = new ModConfigSpec.Builder();
    private static final ModConfigSpec.BooleanValue registerAdamantine = BUILDER.comment("Enable/Disable Adamantine").define("Adamantine",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerAgate = BUILDER.comment("Enable/Disable Agate").define("Agate",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerAldourite = BUILDER.comment("Enable/Disable Aldourite").define("Aldourite",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerAluminum = BUILDER.comment("Enable/Disable Aluminum").define("Aluminum",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerAmericium = BUILDER.comment("Enable/Disable Americium").define("Americium",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerAmethyst = BUILDER.comment("Enable/Disable Amethyst").define("Amethyst",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerAmetrine = BUILDER.comment("Enable/Disable Ametrine").define("Ametrine",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerAmordrine = BUILDER.comment("Enable/Disable Amordrine").define("Amordrine",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerAngmallen = BUILDER.comment("Enable/Disable Angmallen").define("Angmallen",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerAquamarine = BUILDER.comment("Enable/Disable Aquamarine").define("Aquamarine",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerAstralSilver = BUILDER.comment("Enable/Disable Astral Silver").define("Astral_Silver",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerAtlarus = BUILDER.comment("Enable/Disable Atlarus").define("Atlarus",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerAzureSilver = BUILDER.comment("Enable/Disable Azure Silver").define("Azure_Silver",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerBismuth = BUILDER.comment("Enable/Disable Bismuth").define("Bismuth",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerBlackSteel = BUILDER.comment("Enable/Disable Black Steel").define("Black_Steel",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerCadmium = BUILDER.comment("Enable/Disable Cadmium").define("Cadmium",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerCarmot = BUILDER.comment("Enable/Disable Carmot").define("Carmot",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerCelenegil = BUILDER.comment("Enable/Disable Celenegil").define("Celenegil",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerCeruclase = BUILDER.comment("Enable/Disable Ceruclase").define("Ceruclase",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerChromium = BUILDER.comment("Enable/Disable Chromium").define("Chromium",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerChrysocolla = BUILDER.comment("Enable/Disable Chrysocolla").define("Chrysocolla",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerCitrine = BUILDER.comment("Enable/Disable Citrine").define("Citrine",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerCobalt = BUILDER.comment("Enable/Disable Cobalt").define("Cobalt",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerCopper = BUILDER.comment("Enable/Disable Copper").define("Copper",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerCrimsonSteel = BUILDER.comment("Enable/Disable Crimson Steel").define("Crimson_Steel",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerDeepIron = BUILDER.comment("Enable/Disable Deep Iron").define("Deep_Iron",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerDesichalkos = BUILDER.comment("Enable/Disable Desichalkos").define("Desichalkos",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerEximite = BUILDER.comment("Enable/Disable Eximite").define("Eximite",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerGallium = BUILDER.comment("Enable/Disable Gallium").define("Gallium",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerGarnet = BUILDER.comment("Enable/Disable Garnet").define("Garnet",ModInfo.GUI_DEFAULT_VALUE);
    public static final ModConfigSpec SPEC = BUILDER.build();
    public static boolean Adamantine;
    public static boolean Agate;
    public static boolean Aldourite;
    public static boolean Aluminum;
    public static boolean Americium;
    public static boolean Amethyst;
    public static boolean Ametrine;
    public static boolean Amordrine;
    public static boolean Angmallen;
    public static boolean Aquamarine;
    public static boolean AstralSilver;
    public static boolean Atlarus;
    public static boolean AzureSilver;
    public static boolean Bismuth;
    public static boolean BlackSteel;
    public static boolean Cadmium;
    public static boolean Carmot;
    public static boolean Celenegil;
    public static boolean Ceruclase;
    public static boolean Chromium;
    public static boolean Chrysocolla;
    public static boolean Citrine;
    public static boolean Cobalt;
    public static boolean Copper;
    public static boolean CrimsonSteel;
    public static boolean DeepIron;
    public static boolean Desichalkos;
    public static boolean Eximite;
    public static boolean Gallium;
    public static boolean Garnet;
    public static boolean Haderoth;
    public static boolean Hepatizon;
    public static boolean Ignatius;
    public static boolean Indium;
    public static boolean Infuscolium;
    public static boolean Inolashite;
    public static boolean Iolite;
    public static boolean Iridium;
    public static boolean Jade;
    public static boolean Jasper;
    public static boolean Kalendrite;
    public static boolean Kyanite;
    public static boolean Lead;
    public static boolean Lemurite;
    public static boolean Malachite;
    public static boolean Manganese;
    public static boolean Meutoite;
    public static boolean Midasium;
    public static boolean Mithril;
    public static boolean Molybdenum;
    public static boolean Neodymium;
    public static boolean Neptunium;
    public static boolean Nickel;
    public static boolean Niobium;
    public static boolean Onyx;
    public static boolean Opal;
    public static boolean Orichalcum;
    public static boolean Osmium;
    public static boolean Oureclase;
    public static boolean Palladium;
    public static boolean Peridot;
    public static boolean Phoenixite;
    public static boolean Platinum;
    public static boolean Plutonium;
    public static boolean Polonium;
    public static boolean Promethium;
    public static boolean Quartz;
    public static boolean Rhenium;
    public static boolean Rhodium;
    public static boolean Rubracium;
    public static boolean Ruby;
    public static boolean Ruthenium;
    public static boolean Sanguinite;
    public static boolean Sapphire;
    public static boolean ShadowIron;
    public static boolean Silver;
    public static boolean Spinel;
    public static boolean Sugilite;
    public static boolean Tantalum;
    public static boolean Tanzanite;
    public static boolean Tartarite;
    public static boolean Technetium;
    public static boolean Thallium;
    public static boolean Tin;
    public static boolean Titanium;
    public static boolean Topaz;
    public static boolean Tourmaline;
    public static boolean Tritium;
    public static boolean Tungsten;
    public static boolean Turquoise;
    public static boolean Unobtainium;
    public static boolean Uranium;
    public static boolean Vanadium;
    public static boolean Vibranium;
    public static boolean Vulcanite;
    public static boolean Vyroxeres;
    public static boolean Yellorite;
    public static boolean Zinc;
    public static boolean Zirconium;
    public static void initConfig()
    {
        //Adamantine = registerAdamantine.get();
        Adamantine = registerAdamantine.get();
        Agate = registerAgate.get();
        Aldourite = registerAldourite.get();
        Aluminum = registerAluminum.get();
        Americium = registerAmericium.get();
        Amethyst = registerAmethyst.get();
        Ametrine = registerAmetrine.get();
        Amordrine = registerAmordrine.get();
        Angmallen = registerAngmallen.get();
        Aquamarine = registerAquamarine.get();
        AstralSilver = registerAstralSilver.get();
        Atlarus = registerAtlarus.get();
        AzureSilver = registerAzureSilver.get();
        Bismuth = registerBismuth.get();
        BlackSteel = registerBlackSteel.get();
        Cadmium = registerCadmium.get();
        Carmot = registerCarmot.get();
        Celenegil = registerCelenegil.get();
        Ceruclase = registerCeruclase.get();
        Chromium = registerChromium.get();
        Chrysocolla = registerChrysocolla.get();
        Citrine = registerCitrine.get();
        Cobalt = registerCobalt.get();
        Copper = registerCopper.get();
        CrimsonSteel = registerCrimsonSteel.get();
        DeepIron = registerDeepIron.get();
        Desichalkos = registerDesichalkos.get();
        Eximite = registerEximite.get();
        Gallium = registerGallium.get();
        Garnet = registerGarnet.get();
        Haderoth = registerHaderoth.get();
        Hepatizon = registerHepatizon.get();
        Ignatius = registerIgnatius.get();
        Indium = registerIndium.get();
        Infuscolium = registerInfuscolium.get();
        Inolashite = registerInolashite.get();
        Iolite = registerIolite.get();
        Iridium = registerIridium.get();
        Jade = registerJade.get();
        Jasper = registerJasper.get();
        Kalendrite = registerKalendrite.get();
        Kyanite = registerKyanite.get();
        Lead = registerLead.get();
        Lemurite = registerLemurite.get();
        Malachite = registerMalachite.get();
        Manganese = registerManganese.get();
        Meutoite = registerMeutoite.get();
        Midasium = registerMidasium.get();
        Mithril = registerMithril.get();
        Molybdenum = registerMolybdenum.get();
        Neodymium = registerNeodymium.get();
        Neptunium = registerNeptunium.get();
        Nickel = registerNickel.get();
        Niobium = registerNiobium.get();
        Onyx = registerOnyx.get();
        Opal = registerOpal.get();
        Orichalcum = registerOrichalcum.get();
        Osmium = registerOsmium.get();
        Oureclase = registerOureclase.get();
        Palladium = registerPalladium.get();
        Peridot = registerPeridot.get();
        Phoenixite = registerPhoenixite.get();
        Platinum = registerPlatinum.get();
        Plutonium = registerPlutonium.get();
        Polonium = registerPolonium.get();
        Promethium = registerPromethium.get();
        Quartz = registerQuartz.get();
        Rhenium = registerRhenium.get();
        Rhodium = registerRhodium.get();
        Rubracium = registerRubracium.get();
        Ruby = registerRuby.get();
        Ruthenium = registerRuthenium.get();
        Sanguinite = registerSanguinite.get();
        Sapphire = registerSapphire.get();
        ShadowIron = registerShadowIron.get();
        Silver = registerSilver.get();
        Spinel = registerSpinel.get();
        Sugilite = registerSugilite.get();
        Tantalum = registerTantalum.get();
        Tanzanite = registerTanzanite.get();
        Tartarite = registerTartarite.get();
        Technetium = registerTechnetium.get();
        Thallium = registerThallium.get();
        Tin = registerTin.get();
        Titanium = registerTitanium.get();
        Topaz = registerTopaz.get();
        Tourmaline = registerTourmaline.get();
        Tritium = registerTritium.get();
        Tungsten = registerTungsten.get();
        Turquoise = registerTurquoise.get();
        Unobtainium = registerUnobtainium.get();
        Uranium = registerUranium.get();
        Vanadium = registerVanadium.get();
        Vibranium = registerVibranium.get();
        Vulcanite = registerVulcanite.get();
        Vyroxeres = registerVyroxeres.get();
        Yellorite = registerYellorite.get();
        Zinc = registerZinc.get();
        Zirconium = registerZirconium.get();
        
    }
}
