package com.tylerh.extraores.Util;

import net.neoforged.neoforge.common.ModConfigSpec;

public class ExOresConfig
{
    public static ModConfigSpec.Builder BUILDER = new ModConfigSpec.Builder();
    private static final ModConfigSpec.BooleanValue registerAdamantine = BUILDER.comment("Enable/Disable Adamantine").define("Adamantine",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerAgate = BUILDER.comment("Enable/Disable Agate").define("Agate",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerAldourite = BUILDER.comment("Enable/Disable Aldourite").define("Aldourite",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerAluminum = BUILDER.comment("Enable/Disable Aluminum").define("Aluminum",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerAmericium = BUILDER.comment("Enable/Disable Americium").define("Americium",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerAmethyst = BUILDER.comment("Enable/Disable Amethyst").define("Amethyst",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerAmetrine = BUILDER.comment("Enable/Disable Ametrine").define("Ametrine",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerAmordrine = BUILDER.comment("Enable/Disable Amordrine").define("Amordrine",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerAngmallen = BUILDER.comment("Enable/Disable Angmallen").define("Angmallen",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerAquamarine = BUILDER.comment("Enable/Disable Aquamarine").define("Aquamarine",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerAstralSilver = BUILDER.comment("Enable/Disable Astral Silver").define("Astral_Silver",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerAtlarus = BUILDER.comment("Enable/Disable Atlarus").define("Atlarus",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerAzureSilver = BUILDER.comment("Enable/Disable Azure Silver").define("Azure_Silver",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerBismuth = BUILDER.comment("Enable/Disable Bismuth").define("Bismuth",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerBlackSteel = BUILDER.comment("Enable/Disable Black Steel").define("Black_Steel",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerCadmium = BUILDER.comment("Enable/Disable Cadmium").define("Cadmium",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerCarmot = BUILDER.comment("Enable/Disable Carmot").define("Carmot",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerCelenegil = BUILDER.comment("Enable/Disable Celenegil").define("Celenegil",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerCeruclase = BUILDER.comment("Enable/Disable Ceruclase").define("Ceruclase",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerChromium = BUILDER.comment("Enable/Disable Chromium").define("Chromium",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerChrysocolla = BUILDER.comment("Enable/Disable Chrysocolla").define("Chrysocolla",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerCitrine = BUILDER.comment("Enable/Disable Citrine").define("Citrine",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerCobalt = BUILDER.comment("Enable/Disable Cobalt").define("Cobalt",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerCopper = BUILDER.comment("Enable/Disable Copper").define("Copper",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerCrimsonSteel = BUILDER.comment("Enable/Disable Crimson Steel").define("Crimson_Steel",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerDeepIron = BUILDER.comment("Enable/Disable Deep Iron").define("Deep_Iron",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerDesichalkos = BUILDER.comment("Enable/Disable Desichalkos").define("Desichalkos",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerEximite = BUILDER.comment("Enable/Disable Eximite").define("Eximite",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerGallium = BUILDER.comment("Enable/Disable Gallium").define("Gallium",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerGarnet = BUILDER.comment("Enable/Disable Garnet").define("Garnet",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerHaderoth = BUILDER.comment("Enable/Disable Haderoth").define("Haderoth",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerHepatizon = BUILDER.comment("Enable/Disable Hepatizon").define("Hepatizon",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerIgnatius = BUILDER.comment("Enable/Disable Ignatius").define("Ignatius",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerIndium = BUILDER.comment("Enable/Disable Indium").define("Indium",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerInfuscolium = BUILDER.comment("Enable/Disable Infuscolium").define("Infuscolium",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerInolashite = BUILDER.comment("Enable/Disable Inolashite").define("Inolashite",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerIolite = BUILDER.comment("Enable/Disable Iolite").define("Iolite",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerIridium = BUILDER.comment("Enable/Disable Iridium").define("Iridium",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerJade = BUILDER.comment("Enable/Disable Jade").define("Jade",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerJasper = BUILDER.comment("Enable/Disable Jasper").define("Jasper",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerKalendrite = BUILDER.comment("Enable/Disable Kalendrite").define("Kalendrite",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerKyanite = BUILDER.comment("Enable/Disable Kyanite").define("Kyanite",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerLead = BUILDER.comment("Enable/Disable Lead").define("Lead",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerLemurite = BUILDER.comment("Enable/Disable Lemurite").define("Lemurite",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerMalachite = BUILDER.comment("Enable/Disable Malachite").define("Malachite",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerManganese = BUILDER.comment("Enable/Disable Manganese").define("Manganese",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerMeutoite = BUILDER.comment("Enable/Disable Meutoite").define("Meutoite",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerMidasium = BUILDER.comment("Enable/Disable Midasium").define("Midasium",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerMithril = BUILDER.comment("Enable/Disable Mithril").define("Mithril",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerMolybdenum = BUILDER.comment("Enable/Disable Molybdenum").define("Molybdenum",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerNeodymium = BUILDER.comment("Enable/Disable Neodymium").define("Neodymium",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerNeptunium = BUILDER.comment("Enable/Disable Neptunium").define("Neptunium",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerNickel = BUILDER.comment("Enable/Disable Nickel").define("Nickel",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerNiobium = BUILDER.comment("Enable/Disable Niobium").define("Niobium",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerOnyx = BUILDER.comment("Enable/Disable Onyx").define("Onyx",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerOpal = BUILDER.comment("Enable/Disable Opal").define("Opal",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerOrichalcum = BUILDER.comment("Enable/Disable Orichalcum").define("Orichalcum",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerOsmium = BUILDER.comment("Enable/Disable Osmium").define("Osmium",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerOureclase = BUILDER.comment("Enable/Disable Oureclase").define("Oureclase",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerPalladium = BUILDER.comment("Enable/Disable Palladium").define("Palladium",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerPeridot = BUILDER.comment("Enable/Disable Peridot").define("Peridot",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerPhoenixite = BUILDER.comment("Enable/Disable Phoenixite").define("Phoenixite",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerPlatinum = BUILDER.comment("Enable/Disable Platinum").define("Platinum",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerPlutonium = BUILDER.comment("Enable/Disable Plutonium").define("Plutonium",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerPolonium = BUILDER.comment("Enable/Disable Polonium").define("Polonium",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerPromethium = BUILDER.comment("Enable/Disable Promethium").define("Promethium",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerQuartz = BUILDER.comment("Enable/Disable Quartz").define("Quartz",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerRhenium = BUILDER.comment("Enable/Disable Rhenium").define("Rhenium",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerRhodium = BUILDER.comment("Enable/Disable Rhodium").define("Rhodium",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerRubracium = BUILDER.comment("Enable/Disable Rubracium").define("Rubracium",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerRuby = BUILDER.comment("Enable/Disable Ruby").define("Ruby",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerRuthenium = BUILDER.comment("Enable/Disable Ruthenium").define("Ruthenium",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerSanguinite = BUILDER.comment("Enable/Disable Sanguinite").define("Sanguinite",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerSapphire = BUILDER.comment("Enable/Disable Sapphire").define("Sapphire",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerShadowIron = BUILDER.comment("Enable/Disable Shadow Iron").define("Shadow_Iron",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerSilver = BUILDER.comment("Enable/Disable Silver").define("Silver",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerSpinel = BUILDER.comment("Enable/Disable Spinel").define("Spinel",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerSugilite = BUILDER.comment("Enable/Disable Sugilite").define("Sugilite",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerTantalum = BUILDER.comment("Enable/Disable Tantalum").define("Tantalum",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerTanzanite = BUILDER.comment("Enable/Disable Tanzanite").define("Tanzanite",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerTartarite = BUILDER.comment("Enable/Disable Tartarite").define("Tartarite",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerTechnetium = BUILDER.comment("Enable/Disable Technetium").define("Technetium",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerThallium = BUILDER.comment("Enable/Disable Thallium").define("Thallium",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerTin = BUILDER.comment("Enable/Disable Tin").define("Tin",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerTitanium = BUILDER.comment("Enable/Disable Titanium").define("Titanium",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerTopaz = BUILDER.comment("Enable/Disable Topaz").define("Topaz",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerTourmaline = BUILDER.comment("Enable/Disable Tourmaline").define("Tourmaline",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerTritium = BUILDER.comment("Enable/Disable Tritium").define("Tritium",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerTungsten = BUILDER.comment("Enable/Disable Tungsten").define("Tungsten",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerTurquoise = BUILDER.comment("Enable/Disable Turquoise").define("Turquoise",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerUnobtainium = BUILDER.comment("Enable/Disable Unobtainium").define("Unobtainium",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerUranium = BUILDER.comment("Enable/Disable Uranium").define("Uranium",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerVanadium = BUILDER.comment("Enable/Disable Vanadium").define("Vanadium",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerVibranium = BUILDER.comment("Enable/Disable Vibranium").define("Vibranium",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerVulcanite = BUILDER.comment("Enable/Disable Vulcanite").define("Vulcanite",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerVyroxeres = BUILDER.comment("Enable/Disable Vyroxeres").define("Vyroxeres",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerYellorite = BUILDER.comment("Enable/Disable Yellorite").define("Yellorite",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerZinc = BUILDER.comment("Enable/Disable Zinc").define("Zinc",ModInfo.GUI_DEFAULT_VALUE);
    private static final ModConfigSpec.BooleanValue registerZirconium = BUILDER.comment("Enable/Disable Zirconium").define("Zirconium",ModInfo.GUI_DEFAULT_VALUE);
    public static final ModConfigSpec SPEC = BUILDER.build();
    public static boolean Adamantine;
    public static boolean Agate;
    public static boolean Aldourite;
    public static boolean Aluminum;
    public static boolean Americium;
    public static boolean Amethyst;
    public static boolean Ametrine;
    public static boolean Amordrine;
    public static boolean Angmallen;
    public static boolean Aquamarine;
    public static boolean AstralSilver;
    public static boolean Atlarus;
    public static boolean AzureSilver;
    public static boolean Bismuth;
    public static boolean BlackSteel;
    public static boolean Cadmium;
    public static boolean Carmot;
    public static boolean Celenegil;
    public static boolean Ceruclase;
    public static boolean Chromium;
    public static boolean Chrysocolla;
    public static boolean Citrine;
    public static boolean Cobalt;
    public static boolean Copper;
    public static boolean CrimsonSteel;
    public static boolean DeepIron;
    public static boolean Desichalkos;
    public static boolean Eximite;
    public static boolean Gallium;
    public static boolean Garnet;
    public static boolean Haderoth;
    public static boolean Hepatizon;
    public static boolean Ignatius;
    public static boolean Indium;
    public static boolean Infuscolium;
    public static boolean Inolashite;
    public static boolean Iolite;
    public static boolean Iridium;
    public static boolean Jade;
    public static boolean Jasper;
    public static boolean Kalendrite;
    public static boolean Kyanite;
    public static boolean Lead;
    public static boolean Lemurite;
    public static boolean Malachite;
    public static boolean Manganese;
    public static boolean Meutoite;
    public static boolean Midasium;
    public static boolean Mithril;
    public static boolean Molybdenum;
    public static boolean Neodymium;
    public static boolean Neptunium;
    public static boolean Nickel;
    public static boolean Niobium;
    public static boolean Onyx;
    public static boolean Opal;
    public static boolean Orichalcum;
    public static boolean Osmium;
    public static boolean Oureclase;
    public static boolean Palladium;
    public static boolean Peridot;
    public static boolean Phoenixite;
    public static boolean Platinum;
    public static boolean Plutonium;
    public static boolean Polonium;
    public static boolean Promethium;
    public static boolean Quartz;
    public static boolean Rhenium;
    public static boolean Rhodium;
    public static boolean Rubracium;
    public static boolean Ruby;
    public static boolean Ruthenium;
    public static boolean Sanguinite;
    public static boolean Sapphire;
    public static boolean ShadowIron;
    public static boolean Silver;
    public static boolean Spinel;
    public static boolean Sugilite;
    public static boolean Tantalum;
    public static boolean Tanzanite;
    public static boolean Tartarite;
    public static boolean Technetium;
    public static boolean Thallium;
    public static boolean Tin;
    public static boolean Titanium;
    public static boolean Topaz;
    public static boolean Tourmaline;
    public static boolean Tritium;
    public static boolean Tungsten;
    public static boolean Turquoise;
    public static boolean Unobtainium;
    public static boolean Uranium;
    public static boolean Vanadium;
    public static boolean Vibranium;
    public static boolean Vulcanite;
    public static boolean Vyroxeres;
    public static boolean Yellorite;
    public static boolean Zinc;
    public static boolean Zirconium;
    public static void initConfig()
    {
        //Adamantine = registerAdamantine.get();
        Adamantine = registerAdamantine.get();
        Agate = registerAgate.get();
        Aldourite = registerAldourite.get();
        Aluminum = registerAluminum.get();
        Americium = registerAmericium.get();
        Amethyst = registerAmethyst.get();
        Ametrine = registerAmetrine.get();
        Amordrine = registerAmordrine.get();
        Angmallen = registerAngmallen.get();
        Aquamarine = registerAquamarine.get();
        AstralSilver = registerAstralSilver.get();
        Atlarus = registerAtlarus.get();
        AzureSilver = registerAzureSilver.get();
        Bismuth = registerBismuth.get();
        BlackSteel = registerBlackSteel.get();
        Cadmium = registerCadmium.get();
        Carmot = registerCarmot.get();
        Celenegil = registerCelenegil.get();
        Ceruclase = registerCeruclase.get();
        Chromium = registerChromium.get();
        Chrysocolla = registerChrysocolla.get();
        Citrine = registerCitrine.get();
        Cobalt = registerCobalt.get();
        Copper = registerCopper.get();
        CrimsonSteel = registerCrimsonSteel.get();
        DeepIron = registerDeepIron.get();
        Desichalkos = registerDesichalkos.get();
        Eximite = registerEximite.get();
        Gallium = registerGallium.get();
        Garnet = registerGarnet.get();
        Haderoth = registerHaderoth.get();
        Hepatizon = registerHepatizon.get();
        Ignatius = registerIgnatius.get();
        Indium = registerIndium.get();
        Infuscolium = registerInfuscolium.get();
        Inolashite = registerInolashite.get();
        Iolite = registerIolite.get();
        Iridium = registerIridium.get();
        Jade = registerJade.get();
        Jasper = registerJasper.get();
        Kalendrite = registerKalendrite.get();
        Kyanite = registerKyanite.get();
        Lead = registerLead.get();
        Lemurite = registerLemurite.get();
        Malachite = registerMalachite.get();
        Manganese = registerManganese.get();
        Meutoite = registerMeutoite.get();
        Midasium = registerMidasium.get();
        Mithril = registerMithril.get();
        Molybdenum = registerMolybdenum.get();
        Neodymium = registerNeodymium.get();
        Neptunium = registerNeptunium.get();
        Nickel = registerNickel.get();
        Niobium = registerNiobium.get();
        Onyx = registerOnyx.get();
        Opal = registerOpal.get();
        Orichalcum = registerOrichalcum.get();
        Osmium = registerOsmium.get();
        Oureclase = registerOureclase.get();
        Palladium = registerPalladium.get();
        Peridot = registerPeridot.get();
        Phoenixite = registerPhoenixite.get();
        Platinum = registerPlatinum.get();
        Plutonium = registerPlutonium.get();
        Polonium = registerPolonium.get();
        Promethium = registerPromethium.get();
        Quartz = registerQuartz.get();
        Rhenium = registerRhenium.get();
        Rhodium = registerRhodium.get();
        Rubracium = registerRubracium.get();
        Ruby = registerRuby.get();
        Ruthenium = registerRuthenium.get();
        Sanguinite = registerSanguinite.get();
        Sapphire = registerSapphire.get();
        ShadowIron = registerShadowIron.get();
        Silver = registerSilver.get();
        Spinel = registerSpinel.get();
        Sugilite = registerSugilite.get();
        Tantalum = registerTantalum.get();
        Tanzanite = registerTanzanite.get();
        Tartarite = registerTartarite.get();
        Technetium = registerTechnetium.get();
        Thallium = registerThallium.get();
        Tin = registerTin.get();
        Titanium = registerTitanium.get();
        Topaz = registerTopaz.get();
        Tourmaline = registerTourmaline.get();
        Tritium = registerTritium.get();
        Tungsten = registerTungsten.get();
        Turquoise = registerTurquoise.get();
        Unobtainium = registerUnobtainium.get();
        Uranium = registerUranium.get();
        Vanadium = registerVanadium.get();
        Vibranium = registerVibranium.get();
        Vulcanite = registerVulcanite.get();
        Vyroxeres = registerVyroxeres.get();
        Yellorite = registerYellorite.get();
        Zinc = registerZinc.get();
        Zirconium = registerZirconium.get();
        
    }
}
