package com.tylerh.extraores.Init;

import com.tylerh.extraores.Util.ModInfo;
import net.minecraftforge.common.ForgeConfigSpec;

public class ConfigRegistryList
{
    public static ForgeConfigSpec.BooleanValue registerAdamantine;
    public static ForgeConfigSpec.BooleanValue registerAgate;
    public static ForgeConfigSpec.BooleanValue registerAldourite;
    public static ForgeConfigSpec.BooleanValue registerAluminum;
    public static ForgeConfigSpec.BooleanValue registerAmericium;
    public static ForgeConfigSpec.BooleanValue registerAmethyst;
    public static ForgeConfigSpec.BooleanValue registerAmetrine;
    public static ForgeConfigSpec.BooleanValue registerAmordrine;
    public static ForgeConfigSpec.BooleanValue registerAngmallen;
    public static ForgeConfigSpec.BooleanValue registerAquamarine;
    public static ForgeConfigSpec.BooleanValue registerAstralSilver;
    public static ForgeConfigSpec.BooleanValue registerAtlarus;
    public static ForgeConfigSpec.BooleanValue registerBismuth;
    public static ForgeConfigSpec.BooleanValue registerBlackSteel;
    public static ForgeConfigSpec.BooleanValue registerCadmium;
    public static ForgeConfigSpec.BooleanValue registerCarmot;
    public static ForgeConfigSpec.BooleanValue registerCelenegil;
    public static ForgeConfigSpec.BooleanValue registerCeruclase;
    public static ForgeConfigSpec.BooleanValue registerChromium;
    public static ForgeConfigSpec.BooleanValue registerChrysocolla;
    public static ForgeConfigSpec.BooleanValue registerCitrine;
    public static ForgeConfigSpec.BooleanValue registerCobalt;
    public static ForgeConfigSpec.BooleanValue registerCopper;
    public static ForgeConfigSpec.BooleanValue registerDeepIron;
    public static ForgeConfigSpec.BooleanValue registerDesichalkos;
    public static ForgeConfigSpec.BooleanValue registerEximite;
    public static ForgeConfigSpec.BooleanValue registerGallium;
    public static ForgeConfigSpec.BooleanValue registerGarnet;
    public static ForgeConfigSpec.BooleanValue registerHaderoth;
    public static ForgeConfigSpec.BooleanValue registerHepatizon;
    public static ForgeConfigSpec.BooleanValue registerIgnatius;
    public static ForgeConfigSpec.BooleanValue registerIndium;
    public static ForgeConfigSpec.BooleanValue registerInfuscolium;
    public static ForgeConfigSpec.BooleanValue registerInolashite;
    public static ForgeConfigSpec.BooleanValue registerIolite;
    public static ForgeConfigSpec.BooleanValue registerIridium;
    public static ForgeConfigSpec.BooleanValue registerJade;
    public static ForgeConfigSpec.BooleanValue registerJasper;
    public static ForgeConfigSpec.BooleanValue registerKalendrite;
    public static ForgeConfigSpec.BooleanValue registerKyanite;
    public static ForgeConfigSpec.BooleanValue registerLead;
    public static ForgeConfigSpec.BooleanValue registerLemurite;
    public static ForgeConfigSpec.BooleanValue registerMalachite;
    public static ForgeConfigSpec.BooleanValue registerManganese;
    public static ForgeConfigSpec.BooleanValue registerMeutoite;
    public static ForgeConfigSpec.BooleanValue registerMidasium;
    public static ForgeConfigSpec.BooleanValue registerMithril;
    public static ForgeConfigSpec.BooleanValue registerMolybdenum;
    public static ForgeConfigSpec.BooleanValue registerNeodymium;
    public static ForgeConfigSpec.BooleanValue registerNeptunium;
    public static ForgeConfigSpec.BooleanValue registerNickel;
    public static ForgeConfigSpec.BooleanValue registerNiobium;
    public static ForgeConfigSpec.BooleanValue registerOnyx;
    public static ForgeConfigSpec.BooleanValue registerOpal;
    public static ForgeConfigSpec.BooleanValue registerOrichalcum;
    public static ForgeConfigSpec.BooleanValue registerOsmium;
    public static ForgeConfigSpec.BooleanValue registerOureclase;
    public static ForgeConfigSpec.BooleanValue registerPalladium;
    public static ForgeConfigSpec.BooleanValue registerPeridot;
    public static ForgeConfigSpec.BooleanValue registerPhoenixite;
    public static ForgeConfigSpec.BooleanValue registerPlatinum;
    public static ForgeConfigSpec.BooleanValue registerPlutonium;
    public static ForgeConfigSpec.BooleanValue registerPolonium;
    public static ForgeConfigSpec.BooleanValue registerPromethium;
    public static ForgeConfigSpec.BooleanValue registerRhenium;
    public static ForgeConfigSpec.BooleanValue registerRhodium;
    public static ForgeConfigSpec.BooleanValue registerRuthenium;
    public static ForgeConfigSpec.BooleanValue registerRubracium;
    public static ForgeConfigSpec.BooleanValue registerRuby;
    public static ForgeConfigSpec.BooleanValue registerSanguinite;
    public static ForgeConfigSpec.BooleanValue registerSapphire;
    public static ForgeConfigSpec.BooleanValue registerShadowIron;
    public static ForgeConfigSpec.BooleanValue registerSilver;
    public static ForgeConfigSpec.BooleanValue registerSpinel;
    public static ForgeConfigSpec.BooleanValue registerSugilite;
    public static ForgeConfigSpec.BooleanValue registerTantalum;
    public static ForgeConfigSpec.BooleanValue registerTanzanite;
    public static ForgeConfigSpec.BooleanValue registerTartarite;
    public static ForgeConfigSpec.BooleanValue registerTechnetium;
    public static ForgeConfigSpec.BooleanValue registerThallium;
    public static ForgeConfigSpec.BooleanValue registerTin;
    public static ForgeConfigSpec.BooleanValue registerTitanium;
    public static ForgeConfigSpec.BooleanValue registerTopaz;
    public static ForgeConfigSpec.BooleanValue registerTourmaline;
    public static ForgeConfigSpec.BooleanValue registerTungsten;
    public static ForgeConfigSpec.BooleanValue registerTurquoise;
    public static ForgeConfigSpec.BooleanValue registerUnobtainium;
    public static ForgeConfigSpec.BooleanValue registerUranium;
    public static ForgeConfigSpec.BooleanValue registerVanadium;
    public static ForgeConfigSpec.BooleanValue registerVulcanite;
    public static ForgeConfigSpec.BooleanValue registerVyroxeres;
    public static ForgeConfigSpec.BooleanValue registerYellorite;
    public static ForgeConfigSpec.BooleanValue registerZinc;
    public static ForgeConfigSpec.BooleanValue registerZirconium;

    public static void initConfig(ForgeConfigSpec.Builder builder)
    {
        registerAdamantine = builder.comment("Enable/Disable Adamantine").define("Adamantine", ModInfo.GUI_DEFAULT_VALUE);
        registerAgate = builder.comment("Enable/Disable Agate").define("Agate",ModInfo.GUI_DEFAULT_VALUE);
        registerAldourite = builder.comment("Enable/Disable Aldourite").define("Aldourite", ModInfo.GUI_DEFAULT_VALUE);
        registerAluminum = builder.comment("Enable/Disable Aluminum").define("Aluminum", ModInfo.GUI_DEFAULT_VALUE);
        registerAmericium = builder.comment("Enable/Disable Americium").define("Americium",ModInfo.GUI_DEFAULT_VALUE);
        registerAmethyst = builder.comment("Enable/Disable Amethyst").define("Amethyst",ModInfo.GUI_DEFAULT_VALUE);
        registerAmetrine = builder.comment("Enable/Disable Ametrine").define("Ametrine",ModInfo.GUI_DEFAULT_VALUE);
        registerAmordrine = builder.comment("Enable/Disable Amordrine").define("Amordrine", ModInfo.GUI_DEFAULT_VALUE);
        registerAngmallen = builder.comment("Enable/Disable Angmallen").define("Angmallen", ModInfo.GUI_DEFAULT_VALUE);
        registerAquamarine = builder.comment("Enable/Disable Aquamarine").define("Aquamarine",ModInfo.GUI_DEFAULT_VALUE);
        registerAstralSilver = builder.comment("Enable/Disable Astral Silver").define("Astral Silver", ModInfo.GUI_DEFAULT_VALUE);
        registerAtlarus = builder.comment("Enable/Disable Atlarus").define("Atlarus", ModInfo.GUI_DEFAULT_VALUE);
        registerBismuth = builder.comment("Enable/Disable Bismuth").define("Bismuth", ModInfo.GUI_DEFAULT_VALUE);
        registerBlackSteel = builder.comment("Enable/Disable Black Steel").define("Black Steel", ModInfo.GUI_DEFAULT_VALUE);
        registerCadmium = builder.comment("Enable/Disable Cadmium").define("Cadmium", ModInfo.GUI_DEFAULT_VALUE);
        registerCarmot = builder.comment("Enable/Disable Carmot").define("Carmot", ModInfo.GUI_DEFAULT_VALUE);
        registerCelenegil = builder.comment("Enable/Disable Celenegil").define("Celenegil", ModInfo.GUI_DEFAULT_VALUE);
        registerCeruclase = builder.comment("Enable/Disable Ceruclase").define("Ceruclase", ModInfo.GUI_DEFAULT_VALUE);
        registerChromium = builder.comment("Enable/Disable Chromium").define("Chromium", ModInfo.GUI_DEFAULT_VALUE);
        registerChrysocolla = builder.comment("Enable/Disable Chrysocolla").define("Chrysocolla",ModInfo.GUI_DEFAULT_VALUE);
        registerCitrine = builder.comment("Enable/Disable Citrine").define("Citrine",ModInfo.GUI_DEFAULT_VALUE);
        registerCobalt = builder.comment("Enable/Disable Cobalt").define("Cobalt", ModInfo.GUI_DEFAULT_VALUE);
        registerCopper = builder.comment("Enable/Disable Copper").define("Copper", ModInfo.GUI_DEFAULT_VALUE);
        registerDeepIron = builder.comment("Enable/Disable Deep Iron").define("Deep Iron", ModInfo.GUI_DEFAULT_VALUE);
        registerDesichalkos = builder.comment("Enable/Disable Desichalkos").define("Desichalkos",ModInfo.GUI_DEFAULT_VALUE);
        registerEximite = builder.comment("Enable/Disable Eximite").define("Eximite",ModInfo.GUI_DEFAULT_VALUE);
        registerGallium = builder.comment("Enable/Disable Gallium").define("Gallium", ModInfo.GUI_DEFAULT_VALUE);
        registerGarnet = builder.comment("Enable/Disable Garnet").define("Garnet",ModInfo.GUI_DEFAULT_VALUE);
        registerHaderoth = builder.comment("Enable/Disable Haderoth").define("Haderoth", ModInfo.GUI_DEFAULT_VALUE);
        registerHepatizon = builder.comment("Enable/Disable Hepatizon").define("Hepatizon", ModInfo.GUI_DEFAULT_VALUE);
        registerIgnatius = builder.comment("Enable/Disable Ignatius").define("Ignatius", ModInfo.GUI_DEFAULT_VALUE);
        registerIndium = builder.comment("Enable/Disable Indium").define("Indium", ModInfo.GUI_DEFAULT_VALUE);
        registerInfuscolium = builder.comment("Enable/Disable Infuscolium").define("Infuscolium", ModInfo.GUI_DEFAULT_VALUE);
        registerInolashite = builder.comment("Enable/Disable Inolashite").define("Inolashite", ModInfo.GUI_DEFAULT_VALUE);
        registerIolite = builder.comment("Enable/Disable Iolite").define("Iolite",ModInfo.GUI_DEFAULT_VALUE);
        registerIridium = builder.comment("Enable/Disable Iridium").define("Iridium",ModInfo.GUI_DEFAULT_VALUE);
        registerJade = builder.comment("Enable/Disable Jade").define("Jade",ModInfo.GUI_DEFAULT_VALUE);
        registerJasper = builder.comment("Enable/Disable Jasper").define("Jasper",ModInfo.GUI_DEFAULT_VALUE);
        registerKalendrite = builder.comment("Enable/Disable Kalendrite").define("Kalendrite", ModInfo.GUI_DEFAULT_VALUE);
        registerKyanite = builder.comment("Enable/Disable Kyanite").define("Kyanite",ModInfo.GUI_DEFAULT_VALUE);
        registerLead = builder.comment("Enable/Disable Lead").define("Lead", ModInfo.GUI_DEFAULT_VALUE);
        registerLemurite = builder.comment("Enable/Disable Lemurite").define("Lemurite", ModInfo.GUI_DEFAULT_VALUE);
        registerMalachite = builder.comment("Enable/Disable Malachite").define("Malachite",ModInfo.GUI_DEFAULT_VALUE);
        registerManganese = builder.comment("Enable/Disable Manganese").define("Manganese", ModInfo.GUI_DEFAULT_VALUE);
        registerMeutoite = builder.comment("Enable/Disable Meutoite").define("Meutoite",ModInfo.GUI_DEFAULT_VALUE);
        registerMidasium = builder.comment("Enable/Disable Midasium").define("Midasium", ModInfo.GUI_DEFAULT_VALUE);
        registerMithril = builder.comment("Enable/Disable Mithril").define("Mithril", ModInfo.GUI_DEFAULT_VALUE);
        registerMolybdenum = builder.comment("Enable/Disable Molybdenum").define("Molybdenum", ModInfo.GUI_DEFAULT_VALUE);
        registerNeodymium = builder.comment("Enable/Disable Neodymium").define("Neodymium", ModInfo.GUI_DEFAULT_VALUE);
        registerNeptunium = builder.comment("Enable/Disable Neptunium").define("Neptunium",ModInfo.GUI_DEFAULT_VALUE);
        registerNickel = builder.comment("Enable/Disable Nickel").define("Nickel", ModInfo.GUI_DEFAULT_VALUE);
        registerNiobium = builder.comment("Enable/Disable Niobium").define("Niobium", ModInfo.GUI_DEFAULT_VALUE);
        registerOnyx = builder.comment("Enable/Disable Onyx").define("Onyx",ModInfo.GUI_DEFAULT_VALUE);
        registerOpal = builder.comment("Enable/Disable Opal").define("Opal",ModInfo.GUI_DEFAULT_VALUE);
        registerOrichalcum = builder.comment("Enable/Disable Orichalcum").define("Orichalcum", ModInfo.GUI_DEFAULT_VALUE);
        registerOsmium = builder.comment("Enable/Disable Osmium").define("Osmium",ModInfo.GUI_DEFAULT_VALUE);
        registerOureclase = builder.comment("Enable/Disable Oureclase").define("Oureclase", ModInfo.GUI_DEFAULT_VALUE);
        registerPalladium = builder.comment("Enable/Disable Palladium").define("Palladium", ModInfo.GUI_DEFAULT_VALUE);
        registerPeridot = builder.comment("Enable/Disable Peridot").define("Peridot",ModInfo.GUI_DEFAULT_VALUE);
        registerPhoenixite = builder.comment("Enable/Disable Phoenixite").define("Phoenixite",ModInfo.GUI_DEFAULT_VALUE);
        registerPlatinum = builder.comment("Enable/Disable Platinum").define("Platinum", ModInfo.GUI_DEFAULT_VALUE);
        registerPlutonium = builder.comment("Enable/Disable Plutonium").define("Plutonium",ModInfo.GUI_DEFAULT_VALUE);
        registerPolonium = builder.comment("Enable/Disable Polonium").define("Polonium",ModInfo.GUI_DEFAULT_VALUE);
        registerPromethium = builder.comment("Enable/Disable Promethium").define("Promethium", ModInfo.GUI_DEFAULT_VALUE);
        registerRhenium = builder.comment("Enable/Disable Rhenium").define("Rhenium",ModInfo.GUI_DEFAULT_VALUE);
        registerRhodium = builder.comment("Enable/Disable Rhodium").define("Rhodium", ModInfo.GUI_DEFAULT_VALUE);
        registerRubracium = builder.comment("Enable/Disable Rubracium").define("Rubracium", ModInfo.GUI_DEFAULT_VALUE);
        registerRuby = builder.comment("Enable/Disable Ruby").define("Ruby",ModInfo.GUI_DEFAULT_VALUE);
        registerRuthenium = builder.comment("Enable/Disable Ruthenium").define("Ruthenium", ModInfo.GUI_DEFAULT_VALUE);
        registerSanguinite = builder.comment("Enable/Disable Sanguinite").define("Sanguinite", ModInfo.GUI_DEFAULT_VALUE);
        registerSapphire = builder.comment("Enable/Disable Sapphire").define("Sapphire",ModInfo.GUI_DEFAULT_VALUE);
        registerShadowIron = builder.comment("Enable/Disable Shadow Iron").define("Shadow Iron", ModInfo.GUI_DEFAULT_VALUE);
        registerSilver = builder.comment("Enable/Disable Silver").define("Silver", ModInfo.GUI_DEFAULT_VALUE);
        registerSpinel = builder.comment("Enable/Disable Spinel").define("Spinel",ModInfo.GUI_DEFAULT_VALUE);
        registerSugilite = builder.comment("Enable/Disable Sugilite").define("Sugilite",ModInfo.GUI_DEFAULT_VALUE);
        registerTantalum = builder.comment("Enable/Disable Tantalum").define("Tantalum",ModInfo.GUI_DEFAULT_VALUE);
        registerTanzanite = builder.comment("Enable/Disable Tanzanite").define("Tanzanite",ModInfo.GUI_DEFAULT_VALUE);
        registerTartarite = builder.comment("Enable/Disable Tartarite").define("Tartarite",ModInfo.GUI_DEFAULT_VALUE);
        registerTechnetium = builder.comment("Enable/Disable Technetium").define("Technetium", ModInfo.GUI_DEFAULT_VALUE);
        registerThallium = builder.comment("Enable/Disable Thallium").define("Thallium", ModInfo.GUI_DEFAULT_VALUE);
        registerTin = builder.comment("Enable/Disable Tin").define("Tin", ModInfo.GUI_DEFAULT_VALUE);
        registerTitanium = builder.comment("Enable/Disable Titanium").define("Titanium", ModInfo.GUI_DEFAULT_VALUE);
        registerTopaz = builder.comment("Enable/Disable Topaz").define("Topaz",ModInfo.GUI_DEFAULT_VALUE);
        registerTourmaline = builder.comment("Enable/Disable Tourmaline").define("Tourmaline",ModInfo.GUI_DEFAULT_VALUE);
        registerTungsten = builder.comment("Enable/Disable Tungsten").define("Tungsten", ModInfo.GUI_DEFAULT_VALUE);
        registerTurquoise = builder.comment("Enable/Disable Turquoise").define("Turquoise",ModInfo.GUI_DEFAULT_VALUE);
        registerUnobtainium = builder.comment("Enable/Disable Unobtainium").define("Unobtainium", ModInfo.GUI_DEFAULT_VALUE);
        registerUranium = builder.comment("Enable/Disable Uranium").define("Uranium",ModInfo.GUI_DEFAULT_VALUE);
        registerVanadium = builder.comment("Enable/Disable Vanadium").define("Vanadium", ModInfo.GUI_DEFAULT_VALUE);
        registerVulcanite = builder.comment("Enable/Disable Vulcanite").define("Vulcanite", ModInfo.GUI_DEFAULT_VALUE);
        registerVyroxeres = builder.comment("Enable/Disable Vyroxeres").define("Vyroxeres", ModInfo.GUI_DEFAULT_VALUE);
        registerYellorite = builder.comment("Enable/Disable Yellorite").define("Yellorite",ModInfo.GUI_DEFAULT_VALUE);
        registerZinc = builder.comment("Enable/Disable Zinc").define("Zinc", ModInfo.GUI_DEFAULT_VALUE);
        registerZirconium = builder.comment("Enable/Disable Zirconium").define("Zirconium", ModInfo.GUI_DEFAULT_VALUE);
    }
}
